// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using scrap_depot.Data;

#nullable disable

namespace scrap_depot.Migrations
{
    [DbContext(typeof(ScrapContext))]
    [Migration("20261003223829_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("scrap_depot.Models.Scrap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("Deposited")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Scrap");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 25,
                            Deposited = 0,
                            Description = "A large metal bolt.",
                            Name = "Big Bolt",
                            Weight = 19
                        },
                        new
                        {
                            Id = 2,
                            Credits = 46,
                            Deposited = 0,
                            Description = "A large geared axle made of metal.",
                            Name = "Large Axel",
                            Weight = 16
                        },
                        new
                        {
                            Id = 3,
                            Credits = 31,
                            Deposited = 0,
                            Description = "A flat-bottomed round glass flask.",
                            Name = "Flask",
                            Weight = 16
                        },
                        new
                        {
                            Id = 4,
                            Credits = 36,
                            Deposited = 0,
                            Description = "A detached, octaganal sign reading 'STOP'",
                            Name = "Stop Sign",
                            Weight = 29
                        },
                        new
                        {
                            Id = 5,
                            Credits = 61,
                            Deposited = 0,
                            Description = "A yellow rubber duck.",
                            Name = "Rubber Ducky",
                            Weight = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
